started to add git remote support to prompt

diff --git a/modules/prompt/functions/prompt_kasama_setup b/modules/prompt/functions/prompt_kasama_setup
--- a/modules/prompt/functions/prompt_kasama_setup
+++ b/modules/prompt/functions/prompt_kasama_setup
@@ -38,6 +38,8 @@ LIGHTNING="\u26a1"
 GEAR="\u2699"
 DANGER="\u26a0"
 CURVY="\u2771"
+NEED_PUSH="⇡"
+NEED_PULL="⇣"
 
 # show prompt line start
 prompt_prompt() {
@@ -49,27 +51,27 @@ prompt_prompt() {
 # Takes two arguments, background and foreground. Both can be omitted,
 # rendering default background/foreground.
 prompt_segment() {
-  local bg fg
-  [[ -n $1 ]] && bg="%K{$1}" || bg="%k"
-  [[ -n $2 ]] && fg="%F{$2}" || fg="%f"
-  if [[ $CURRENT_BG != 'NONE' && $1 != $CURRENT_BG ]]; then
-    print -n "%{$bg%F{$CURRENT_BG}%}$SEGMENT_SEPARATOR%{$fg%}"
-  else
-    print -n "%{$bg%}%{$fg%}"
-  fi
-  CURRENT_BG=$1
-  [[ -n $3 ]] && print -n $3
+	local bg fg
+	[[ -n $1 ]] && bg="%K{$1}" || bg="%k"
+	[[ -n $2 ]] && fg="%F{$2}" || fg="%f"
+	if [[ $CURRENT_BG != 'NONE' && $1 != $CURRENT_BG ]]; then
+		print -n "%{$bg%F{$CURRENT_BG}%}$SEGMENT_SEPARATOR%{$fg%}"
+	else
+		print -n "%{$bg%}%{$fg%}"
+	fi
+	CURRENT_BG=$1
+	[[ -n $3 ]] && print -n $3
 }
 
 # End the prompt, closing any open segments
 prompt_end() {
-  if [[ -n $CURRENT_BG ]]; then
-    print -n "%{%k%F{$CURRENT_BG}%}$SEGMENT_SEPARATOR"
-  else
-    print -n "%{%k%}"
-  fi
-  print -n "%{%f%}"
-  CURRENT_BG=''
+	if [[ -n $CURRENT_BG ]]; then
+		print -n "%{%k%F{$CURRENT_BG}%}$SEGMENT_SEPARATOR"
+	else
+		print -n "%{%k%}"
+	fi
+	print -n "%{%f%}"
+	CURRENT_BG=''
 }
 
 ### Prompt components
@@ -77,45 +79,63 @@ prompt_end() {
 
 # Context: user@hostname (who am I and where am I)
 prompt_context() {
-  local user=`whoami`
+	local user=`whoami`
 
-  if [[ "$user" != "$DEFAULT_USER" || -n "$SSH_CONNECTION" ]]; then
-    prompt_segment $PRIMARY_FG default " %(!.%{%F{yellow}%}.)%m "
-  fi
+	if [[ "$user" != "$DEFAULT_USER" || -n "$SSH_CONNECTION" ]]; then
+		prompt_segment $PRIMARY_FG default " %(!.%{%F{yellow}%}.)%m "
+	fi
 }
 
 # Git: branch/detached head, dirty status
 prompt_git() {
-  local color ref
-  is_dirty() {
-    test -n "$(git status --porcelain --ignore-submodules)"
-  }
-	is_up_to_date() {
-		#TODO git coiso (lembre do ~/.scripts/gitinfo)
-		test -n "$(git coisas)"
+	local color ref
+	is_dirty() {
+		test -n "$(git status --porcelain --ignore-submodules)"
 	}
-  ref="$vcs_info_msg_0_"
-  if [[ -n "$ref" ]]; then
-    if is_dirty; then
-      color=yellow
-      ref="${ref} $PLUSMINUS"
-    else
-      color=green
-      ref="${ref} "
-    fi
-    if [[ "${ref/.../}" == "$ref" ]]; then
-      ref="$BRANCH $ref"
-    else
-      ref="$DETACHED ${ref/.../}"
-    fi
-    prompt_segment $color $PRIMARY_FG
-    print -Pn " $ref"
-  fi
+	is_git_up_to_date() {
+		#TODO git coiso (lembre do ~/.scripts/gitinfo)
+		# ATTENTION! return 1 is false, 0 is true
+		command git rev-parse --abbrev-ref @'{u}' &>/dev/null || return 1
+
+		local arrows=""
+		local status
+		arrow_status="$(command git rev-list --left-right --count HEAD...@'{u}' 2>/dev/null)"
+
+		# do nothing if the command failed
+		(( !$? )) || return 1
+
+		return 0
+
+	}
+	ref="$vcs_info_msg_0_"
+	if [[ -n "$ref" ]]; then
+		if is_dirty; then
+			color=yellow
+			ref="${ref} $PLUSMINUS"
+		else
+			color=green
+			ref="${ref} "
+		fi
+		if [[ "${ref/.../}" == "$ref" ]]; then
+			ref="$BRANCH $ref"
+		else
+			ref="$DETACHED ${ref/.../}"
+		fi
+		if [[ is_git_up_to_date  ]]; then
+			arrow_status=(${(ps:\t:)arrow_status})
+			local left=${arrow_status[1]} right=${arrow_status[2]}
+			(( ${right:-0} > 0 )) && right="$NEED_PUSH"
+			(( ${left:-0} > 0 )) && left="$NEED_PULL"
+			ref="${ref}${left}${right}"
+		fi
+		prompt_segment $color $PRIMARY_FG
+		print -Pn " $ref"
+	fi
 }
 
 # Dir: current working directory
 prompt_dir() {
-  prompt_segment blue $PRIMARY_FG ' %~ '
+	prompt_segment blue $PRIMARY_FG ' %~ '
 }
 
 # Status:
@@ -123,44 +143,44 @@ prompt_dir() {
 # - am I root
 # - are there background jobs?
 prompt_status() {
-  local symbols
-  symbols=()
-  [[ $RETVAL -ne 0 ]] && symbols+="%{%F{red}%}$CROSS"
-  [[ $UID -eq 0 ]] && symbols+="%{%F{yellow}%}$LIGHTNING"
-  [[ $(jobs -l | wc -l) -gt 0 ]] && symbols+="%{%F{cyan}%}$GEAR"
+	local symbols
+	symbols=()
+	[[ $RETVAL -ne 0 ]] && symbols+="%{%F{red}%}$CROSS"
+	[[ $UID -eq 0 ]] && symbols+="%{%F{yellow}%}$LIGHTNING"
+	[[ $(jobs -l | wc -l) -gt 0 ]] && symbols+="%{%F{cyan}%}$GEAR"
 
-  [[ -n "$symbols" ]] && prompt_segment $PRIMARY_FG default " $symbols "
+	[[ -n "$symbols" ]] && prompt_segment $PRIMARY_FG default " $symbols "
 }
 
 ## Main prompt
 prompt_agnoster_main() {
-  RETVAL=$?
-  CURRENT_BG='NONE'
-  #prompt_status
-  prompt_context
-  prompt_dir
-  prompt_git
-  prompt_end
+	RETVAL=$?
+	CURRENT_BG='NONE'
+	#prompt_status
+	prompt_context
+	prompt_dir
+	prompt_git
+	prompt_end
 	prompt_prompt
 }
 
 prompt_agnoster_precmd() {
-  vcs_info
-  PROMPT='%{%f%b%k%}$(prompt_agnoster_main) '
+	vcs_info
+	PROMPT='%{%f%b%k%}$(prompt_agnoster_main) '
 }
 
 prompt_agnoster_setup() {
-  autoload -Uz add-zsh-hook
-  autoload -Uz vcs_info
+	autoload -Uz add-zsh-hook
+	autoload -Uz vcs_info
 
-  prompt_opts=(cr subst percent)
+	prompt_opts=(cr subst percent)
 
-  add-zsh-hook precmd prompt_agnoster_precmd
+	add-zsh-hook precmd prompt_agnoster_precmd
 
-  zstyle ':vcs_info:*' enable git
-  zstyle ':vcs_info:*' check-for-changes false
-  zstyle ':vcs_info:git*' formats '%b'
-  zstyle ':vcs_info:git*' actionformats '%b (%a)'
+	zstyle ':vcs_info:*' enable git
+	zstyle ':vcs_info:*' check-for-changes false
+	zstyle ':vcs_info:git*' formats '%b'
+	zstyle ':vcs_info:git*' actionformats '%b (%a)'
 }
 
 prompt_agnoster_setup "$@"
